project_id = "spdlcavcdqsfmwipeqkp"

[functions.jupiter-ai]
verify_jwt = false

[functions.copy-trade]
verify_jwt = false

[functions.copy-trade-webhook]
verify_jwt = false

[functions.auto-trader]
verify_jwt = false

[functions.ai-profit-analysis]
verify_jwt = false

[functions.check-admin]
verify_jwt = false

[functions.rpc-proxy]
verify_jwt = false

[functions.wallet-auth]
verify_jwt = false

[functions.beach-mode]
verify_jwt = false
